services:
  webserver:
    container_name: "$DOCKER_PREFIX-php-apache"
    build:
      context: .
      target: release
    expose:
      - 80
      - 443
    volumes:
      - web_temp_storage:/tmp
      - web_uploads_storage:/var/uploads
    env_file:
      - .production.env
    depends_on:
      - database
    links:
      - database
  database:
    container_name: "$DOCKER_PREFIX-mariadb"
    image: mariadb:latest
    expose:
      - 3306
    volumes:
      - db_storage:/var/lib/mysql
    env_file:
      - .init.env
      - .production.env
volumes:
  db_storage:
    name: "$DOCKER_PREFIX-mariadb-volume"
  web_temp_storage:
    name: "$DOCKER_PREFIX-web-temp-volume"
  web_uploads_storage:
    name: "$DOCKER_PREFIX-web-uploads-volume"