services:
  webserver:
    container_name: "$DOCKER_PREFIX-php-apache"
    build:
      context: .
      target: release
    expose:
      - 80
      - 443
    volumes:
      - web_temp_storage:/tmp
      - web_uploads_storage:/var/uploads
    env_file:
      - .production.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.$DOCKER_PREFIX-http.rule=Host(`$WWW_DOMAIN`)"
      - "traefik.http.routers.$DOCKER_PREFIX-http.entrypoints=web"
      - "traefik.http.routers.$DOCKER_PREFIX-http.middlewares=$DOCKER_PREFIX-https"
      - "traefik.http.middlewares.$DOCKER_PREFIX-https.redirectscheme.scheme=https"
      - "traefik.http.routers.$DOCKER_PREFIX.rule=Host(`$WWW_DOMAIN`)"
      - "traefik.http.routers.$DOCKER_PREFIX.entrypoints=websecure"
      - "traefik.http.routers.$DOCKER_PREFIX.tls=true"
      - "traefik.http.services.$DOCKER_PREFIX-httpd.loadbalancer.server.port=80"
      - "traefik.http.services.$DOCKER_PREFIX-httpd.loadbalancer.passhostheader=true"
    networks:
      - default
    links:
      - database
  database:
    container_name: "$DOCKER_PREFIX-mariadb"
    image: mariadb:latest
    expose:
      - 3306
    ports:
      - "43306:3306"
    volumes:
      - db_storage:/var/lib/mysql
    env_file:
      - .init.env
      - .production.env
    networks:
      - management
networks:
  default:
    name: proxy-network
    external: true
  management:
    name: mgmt-network
    external: true
volumes:
  db_storage:
    name: "$DOCKER_PREFIX-mariadb-volume"
  web_temp_storage:
    name: "$DOCKER_PREFIX-web-temp-volume"
  web_uploads_storage:
    name: "$DOCKER_PREFIX-web-uploads-volume"